### ISSUE TITLE
Binding site bb documentation ligand property

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_vs#2]
In the ligand property of the bindingsite bb, it says:

*Ligand to be found in the protein structure. If no ligand provided,* ***no action will be executed.***

Actually, the binding site is searched and the bb is returning the residues, even if no ligand is provided. 

Maybe needs rephrasing? 

Thanks!

**Comment by gbayarri** [comment]
Modified by:

_Ligand to be found in the protein structure. If no ligand provided, **the largest one will be selected, if more than one**._
