### ISSUE TITLE
Addition of "exhaustiveness" option for vina run

### ISSUE THREAD

**Issue by PabloNA97** [bioexcel/biobb_vs#7]
The default value of **exhaustiveness** when running Autodock Vina is 8. 

At least in some cases, using a lower value of exhaustiveness may lead to similarly good results while reducing substantially the computational effort. Thus it would be very interesting to have this parameter available at the Biobb level so it can be lowered when doing high-thoughput virtual screenings. 

This option can be implemented similarly to the --cpu option that is already available.

You may search for _--exhaustiveness_ in the [Autodock Vina manual](https://vina.scripps.edu/manual/#screening).

Thank you! :)

**Comment by gbayarri** [comment]
Hi @PabloNA97 which range can have this property? 0-10, 1-100?

Thanks!

**Comment by PabloNA97** [comment]
From what I understand in the following [manual](https://autodock-vina.readthedocs.io/en/latest/faq.html), exhaustiveness controls the number of runs of the search algorithm: _"...the number of runs is set by the exhaustiveness parameter..."_

So I guess the answer would be 1 or greater than 1.

**Comment by PabloNA97** [comment]
Thank you very much! :)
